repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: trailing-whitespace
        name: Trim Trailing Whitespace
        description: This hook trims trailing whitespace
        entry: trailing-whitespace-fixer
        types: [text]
    -   id: check-docstring-first
    -   id: check-added-large-files
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        description: Sort imports alphabetically
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
        args: [--line-length=79]
        description: The uncompromising Python code formatter
-   repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
    -   id: docformatter
        description: Formats docstring to follow PEP 257
    -   id: docformatter-venv
        discription: Formats docstring to follow PEP 257. Uses python -m venv.
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.37.3
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
        description: Automatically upgrade syntax for newer versions
-   repo: https://github.com/asottile/dead
    rev: v1.5.0
    hooks:
    -   id: dead
        discription: Dead code detection

#-   repo: local
#    hooks:
#    -   id: pylint
#        name: pylint
#        entry: poetry run pylint src/propn_identification.py
#        language: system
#        always_run: true
#        pass_filenames: false
